############
#  Server  #
############
[server.info]
name = 'Practical Python'
website = 'https://xarlos89.github.io/PracticalPython/'
email = 'Practicalpython-staff@pm.me'
review = 'https://disboard.org/review/create/900302240559018015'
invite = 'https://discord.gg/vgZmgNwuHw'
logo = "https://raw.githubusercontent.com/Xarlos89/PracticalPython/main/logo.png"
id = 1031644670436061324

############
# Channels #
############
[channels.moderation]
verification_channel = 1055126587512721439
quarantine_channel = 1055126882691076177
role_channel = 1062268986726813758
rules_channel = 1062269049121275914
server_support = 1068103243734994964

[channels.normal_channel]
general_channel = 1031644670436061327
resources_channel = 1062300735338983485
python_help_1 = 1062302503351365632
python_help_2 = 12345
challenges_channel = 1045104938071633994
news_channel = 1071095960538718261

[channels.log_channel]
server_change_log = 1062269270047862884
verification_log = 1043621605940674580
chat_log = 1043607758685089932
mod_log = 1055124663526752297
join_log = 1043967844934762556
user_log = 1044331443884654692
zorak_log = 1062754277543645324

#############
#   Roles   #
#############
[user_roles.admin]
owner = 1054762426614157354
admin = 1134861924882989097
staff = 1031903615310385232
staff_networking = 1134861783358775367
project_manager = 1065623556135854160
bot = 1054763353538576437

[user_roles.elevated]
project_manager = 1065909282496847882
community_contributor = 1062269767530065930
helpful = 1062269787914375168
challenger = 1062269799251574804
active_participant = 1062269807086555208

[user_roles.verified]
verified = 1173219859878924298

[user_roles.bad]
muted = 1062270105339301938
naughty = 1062270109839790110

[user_roles.fun]
beginner = 1064259543250522112
intermediate = 1064259555497877534
professional = 1064259557049761863

north_america = 1064259558819770379
europe = 1064259561302794361
asia = 1064259687924637768
africa = 1064259690948722708
south_america = 1064259693545013288
oceana = 1064259760674840666

[user_roles.employment]
open_to_work = 1114611004182102218
employer = 1114611092677722113

#############
# RSS Feeds #
#############
[rss_feeds.links]
jetbrains = 'https://blog.jetbrains.com/pycharm/feed/'
Python_Software_foundation = 'https://feeds.feedburner.com/PythonSoftwareFoundationNews'
