############
#  Server  #
############
[server.info]
name = 'Practical Python'
website = 'https://xarlos89.github.io/PracticalPython/'
email = 'Practicalpython-staff@pm.me'
review = 'https://disboard.org/review/create/900302240559018015'
invite = 'https://discord.gg/vgZmgNwuHw'
logo = "https://raw.githubusercontent.com/Xarlos89/PracticalPython/main/logo.png"
id = 900302240559018015

############
# Channels #
############
[channels.moderation]
verification_channel = 953545059888930816
quarantine_channel = 953647309609132102
role_channel = 965927411273302076
rules_channel = 953583540044443689
server_support = 1068489441527730196

[channels.normal_channel]
general_channel = 953576255435997234
resources_channel = 953583598429171742
python_help_1 = 903542455675260928
python_help_2 = 903542494409674803
challenges_channel = 1045104938071633994
news_channel = 1071848336442794094

[channels.log_channel]
server_change_log = 953545221260595280
verification_log = 1044302239616991242
chat_log = 954023390375710751
mod_log = 1055501831800889454
join_log = 953543179133665380
user_log = 953552502937243679
zorak_log = 1055927534509895701

#############
#   Roles   #
#############
[user_roles.admin]
owner = 920312909110853642
admin = 1129772106914201650
staff = 960232134356901959
staff_networking = 1120793016882434209
bot = 1024923612966309990
zorak = 951025643657777155

[user_roles.elevated]
project_manager = 1065623556135854160
community_contributor = 1025032149679755264
helpful = 940547307194179644
challenger = 1048940634779689062
active_participant = 954308504708075570

[user_roles.unverified]
needs_approval = 935466692316917770

[user_roles.bad]
muted = 996770748825870376
naughty = 930832647742185472

[user_roles.fun]
beginner = 965926311539388457
intermediate = 965926533984288778
professional = 965926542481956906

north_america = 974950715892072488
europe = 974950822133776425
asia = 974950853452636200
africa = 974950895387303977
south_america = 974950944586489856
oceana = 974951025050025984

[user_roles.employment]
open_to_work = 1113020825596067850
employer = 1113020504148815944

#############
# RSS Feeds #
#############
[rss_feeds.links]
jetbrains = 'https://blog.jetbrains.com/pycharm/feed/'
Python_Software_foundation = 'https://feeds.feedburner.com/PythonSoftwareFoundationNews'
